### ISSUE TITLE
Add Endpoint for RIC and local TX only transmission

### ISSUE THREAD

**Issue by dh3wr** [dapnet-core/call-service#2]
Der Call-Service muss für die Sendungen zu Rubriken auch die Eingabe der RIC direkt erlauben. Diese ist bei den Skypern z.B. 5420 und 4512, für die Non-Skyper 1000 bis 1095
Ebenfalls für die Uhrzeit ist ebenfalls eine RIC notwendig.
Vielleicht einen weiteren Endpunkt machen, der Low-Level Calls entgegen nimmt.
expires_on und priority bleiben vorhanden.

**Comment by dh3wr** [comment]
Dieser neue Endpunkt könnte auch implizit Local only distribution sein.
Beispiel für JSON Payload:
{
  data: "ahsdjkhl",
  expires_on: <ISO String>,
  priority: 2
  ric: 4520
  function: 2 (0 bis 3)
}

**Comment by dh3wr** [comment]
Noch was: Für die Zeitaussendung muss auch eine Unterscheidung "alphanum" oder "num" übergeben werden können.

**Comment by dh3wr** [comment]
Es fehlt bei näherer Betrachtung auch noch die Distribution-Angabe, damit auch nur die Sender, die es betrifft aus der Menge der lokal verbundenen Sender den Call erhalten.
Also zusammengefasst:
````
{
data: 'ahsdjkhl',
expires_on: <ISO-Format>,
priority: 2
ric: 4520
function: 2 (0 bis 3)
type: alphanumeric
distribution:  {
  transmitter_groups: [],
  transmitters: []
  }
}
````

**Comment by 7h0ma5** [comment]
Der `POST /calls`-Endpunkt wurde jetzt um folgende Parameter erweitert:

- `local` (boolean): Gibt an, ob der Ruf nur lokal verbreitet werden soll
- `distribution.pocsag` (array): Bietet die Möglichkeit, POCSAG-Adressen direkt anzugeben. Beispiel: `{"ric": 21231, "function": 2}`

Hier ein komplettes Beispiel:
```json
{
    "priority": 4, 
    "data": "Hallo Welt",
    "local": true, 
    "recipients": {
        "pocsag": [
            {"ric": 1234, "function": 2},
            {"ric": 5678, "function": 1}
        ]
    },
    "distribution": {
        "transmitters": ["dl2ic"],
        "transmitter_groups": ["dl.nw"]
    }
}
```

**Comment by 7h0ma5** [comment]
Ein Problem ist, dass die normale HTTP-Authentifizierung noch aktiv ist. Eine Option wäre, die für lokale Docker-IP-Adressen zu deaktivieren.

**Comment by dh3wr** [comment]
Das wäre super mit den Docker-IPs ohne Auth

**Comment by dh3wr** [comment]
Is `local` mandatory or (optional and default = `false`)?

**Comment by dh3wr** [comment]
Ok, selbst gesehen
`` "local" => %{"type" => "boolean", "default" => "false"},``
